workflows:
  my-workflow:
    name: Flutter IOS
    labels:
      - QA
      - ${TENANT_NAME}
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - group_name
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - name: Install dependencies
        script: |
          flutter packages get
      - name: Run tests
        script: |
          flutter test
      - name: Build APK
        script: |
          flutter build apk
      - name: Build iOS
        script: |
          flutter build ios
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/bundle/**/*.aab
    artifacts:
      - build/**/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - vishant.sharma@opstree.com
      scripts:
        - echo 'successfully build ios using flutter'
